/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import list.listdistri;
import list.listuser;

/**
 *
 * @author Wahyu
 */
public class brngmsk extends javax.swing.JPanel {

    /**
     * Creates new form brngmsk
     */
    private Connection conn;
    public brngmsk() {
        initComponents();
        conn = Koneksi.getConnection();
        getData();
        tanggal();
    }
    
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tb_brgmsk.getModel();
        model.setRowCount(0);
        
        try{
            String sql = "Select * From tbl_barangmasuk";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()){
                String no_msk = rs.getString("no_masuk");
                String tgl_msk = rs.getString("tgl_masuk");
                String id_diss = rs.getString("id_distributor");
                String id_uss = rs.getString("id_pengguna");
                
                
                
                Object[] rowData = {no_msk, tgl_msk, id_diss, id_uss};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
            
        } catch (Exception e){
            Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void resetForm() {
       txt_nmrmsk.setText("");
       txt_tglmsk.setText("");
       txt_iddiss.setText("");
       txt_iduss.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dtlbrg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nmrmsk = new javax.swing.JTextField();
        txt_tglmsk = new javax.swing.JTextField();
        txt_iddiss = new javax.swing.JTextField();
        txt_iduss = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_brgmsk = new javax.swing.JTable();
        btn_cancel = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));

        pn_dtlbrg.setBackground(new java.awt.Color(255, 255, 255));
        pn_dtlbrg.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BARANG MASUK COFFE SHOP");

        jLabel2.setText("No. Masuk");

        jLabel3.setText("Tanggal Masuk");

        jLabel4.setText("ID Distributor");

        jLabel5.setText("ID Pengguna");

        txt_tglmsk.setEnabled(false);

        tb_brgmsk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Masuk", "Tanggal Masuk", "ID Distributor", "ID Pengguna"
            }
        ));
        tb_brgmsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_brgmskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_brgmsk);

        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txt_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cariMouseClicked(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        jButton1.setText("--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dtlbrgLayout = new javax.swing.GroupLayout(pn_dtlbrg);
        pn_dtlbrg.setLayout(pn_dtlbrgLayout);
        pn_dtlbrgLayout.setHorizontalGroup(
            pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nmrmsk)
                            .addComponent(txt_tglmsk)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dtlbrgLayout.createSequentialGroup()
                                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_iduss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txt_iddiss))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))))
                    .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel)))
                .addGap(18, 18, 18)
                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addComponent(txt_cari))
                .addContainerGap())
            .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dtlbrgLayout.setVerticalGroup(
            pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nmrmsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dtlbrgLayout.createSequentialGroup()
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tglmsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_iddiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_iduss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel)
                            .addComponent(btn_hapus)
                            .addComponent(btn_update)
                            .addComponent(btn_save))
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dtlbrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dtlbrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cariMouseClicked
        txt_cari.setText("");
    }//GEN-LAST:event_txt_cariMouseClicked

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
         DefaultTableModel model = (DefaultTableModel) tb_brgmsk.getModel();
        model.setRowCount(0);
        
        String cari = txt_cari.getText();
        
        try{
            String sql = "Select * From tbl_barangmasuk WHERE no_masuk LIKE ?  OR tgl_masuk LIKE ? OR id_distributor LIKE ? OR id_pengguna LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1,"%" + cari + "%");
            st.setString(2,"%" + cari + "%");
            st.setString(3,"%" + cari + "%");
            st.setString(4,"%" + cari + "%");
            ResultSet rs = st.executeQuery();
            
            while(rs.next()){
                String no_msk = rs.getString("no_masuk");
                String tgl_msk = rs.getString("tgl_masuk");
                String id_diss = rs.getString("id_distributor");
                String id_uss = rs.getString("id_pengguna");

                
                
                Object[] rowData = {no_msk, tgl_msk, id_diss, id_uss};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
            
        } catch (Exception e){
            Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int selectedRow = tb_brgmsk.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Diperbarui");
    return;
}

String no_msk = txt_nmrmsk.getText();
String tgl_msk = txt_tglmsk.getText();
String id_diss = txt_iddiss.getText();
String id_uss = txt_iduss.getText();

if (no_msk.isEmpty() || tgl_msk.isEmpty() || id_diss.isEmpty() || id_uss.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi", "VALIDASI", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    String sql = "UPDATE tbl_barangmasuk SET no_masuk=?, tgl_masuk=?, id_distributor=?, id_pengguna=? WHERE no_masuk=?";
    PreparedStatement st = conn.prepareStatement(sql);

    st.setString(1, no_msk);
    st.setString(2, tgl_msk);
    st.setString(3, id_diss);
    st.setString(4, id_uss);
    st.setString(5, no_msk);

    int rowUpdate = st.executeUpdate();
    if (rowUpdate > 0) {
        JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
        resetForm();
        getData();
    }

    st.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Gagal melakukan pembaruan data: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Format angka tidak valid: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
}

DefaultTableModel model = (DefaultTableModel) tb_brgmsk.getModel();
model.fireTableDataChanged();

//pn_dtlbrg.removeAll();
//pn_dtlbrg.repaint();
//pn_dtlbrg.revalidate();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String no_msk = txt_nmrmsk.getText();
        String tgl_msk = txt_tglmsk.getText();
        String id_diss = txt_iddiss.getText();
        String id_uss = txt_iduss.getText();

        if(no_msk.isEmpty()||tgl_msk.isEmpty() ||id_diss.isEmpty() ||id_uss.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO tbl_barangmasuk (no_masuk, tgl_masuk, id_distributor, id_pengguna) VALUES(?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, no_msk);
            st.setString(2, tgl_msk);
            st.setString(3, id_diss);
            st.setString(4, id_uss);

            int rowInserted = st.executeUpdate();
            if(rowInserted > 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");

                resetForm();
                getData();
            }

            st.close();
        } catch (Exception e) {
            Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tb_brgmsk.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Dihapus");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapus Data Ini?", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if(confirm ==  JOptionPane.YES_OPTION){
            String no_msk = tb_brgmsk.getValueAt(selectedRow, 0).toString();
            
            try {
                String sql = "DELETE FROM tbl_barangmasuk WHERE no_masuk=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, no_msk);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    resetForm();
                    getData();
                }
                
                st.close();
            } catch (Exception e) {
                Logger.getLogger(brngmsk.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tb_brgmskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_brgmskMouseClicked
        // TODO add your handling code here:
        int selectedRow = tb_brgmsk.getSelectedRow();
        if(selectedRow != -1){
            String no_masuk = tb_brgmsk.getValueAt(selectedRow, 0).toString();
            String tgl = tb_brgmsk.getValueAt(selectedRow, 1).toString();
            String iddis = tb_brgmsk.getValueAt(selectedRow, 2).toString();
            String iduser = tb_brgmsk.getValueAt(selectedRow, 3).toString();
            
            

        
            txt_nmrmsk.setText(no_masuk);
            txt_tglmsk.setText(tgl);
            txt_iddiss.setText(iddis);
            txt_iduss.setText(iduser);
        }
        
    }//GEN-LAST:event_tb_brgmskMouseClicked

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        txt_nmrmsk.setText("");
        txt_iddiss.setText("");
        txt_iduss.setText("");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new listuser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new listdistri().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_dtlbrg;
    private javax.swing.JTable tb_brgmsk;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_iddiss;
    private javax.swing.JTextField txt_iduss;
    private javax.swing.JTextField txt_nmrmsk;
    private javax.swing.JTextField txt_tglmsk;
    // End of variables declaration//GEN-END:variables

    private void tanggal() {
    txt_tglmsk.setEditable(false);
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        txt_tglmsk.setText(tanggal);
    }
}
