/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.Koneksi;
//import static config.Koneksi.conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import list.listuser;

/**
 *
 * @author Wahyu
 */
public class brngklr extends javax.swing.JPanel {

    /**
     * Creates new form brngklr
     */
    private Connection conn;
    public brngklr() {
        initComponents();
        conn = Koneksi.getConnection();
        getData();
        tanggal();
    }
    
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tb_brgklr.getModel();
        model.setRowCount(0);
        
        try{
            String sql = "Select * From tbl_barangkeluar";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()){
                String no_klr = rs.getString("no_keluar");
                String tgl_klr = rs.getString("tgl_keluar");
                String ttl_klr = rs.getString("total_keluar");
                String id_uss = rs.getString("id_pengguna");
                
                
                
                Object[] rowData = {no_klr, tgl_klr, ttl_klr, id_uss};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
            
        } catch (Exception e){
            Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void resetForm() {
       txt_nmrklr.setText("");
       txt_tglklr.setText("");
       txt_ttlklr.setText("");
       txt_iduss.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dtlbrgklr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nmrklr = new javax.swing.JTextField();
        txt_tglklr = new javax.swing.JTextField();
        txt_ttlklr = new javax.swing.JTextField();
        txt_iduss = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_brgklr = new javax.swing.JTable();
        btn_cancel = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_savee = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));

        pn_dtlbrgklr.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BARANG KELUAR COFFE SHOP");

        jLabel2.setText("No. Keluar");

        jLabel3.setText("Tanggal Keluar");

        jLabel4.setText("Total Keluar");

        jLabel5.setText("ID Pengguna");

        txt_tglklr.setEnabled(false);

        tb_brgklr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Keluar", "Tanggal Keluar", "Total Keluar", "ID Pengguna"
            }
        ));
        tb_brgklr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_brgklrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_brgklr);

        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_savee.setText("SAVE");
        btn_savee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveeActionPerformed(evt);
            }
        });

        txt_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cariMouseClicked(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        jButton1.setText("--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dtlbrgklrLayout = new javax.swing.GroupLayout(pn_dtlbrgklr);
        pn_dtlbrgklr.setLayout(pn_dtlbrgklrLayout);
        pn_dtlbrgklrLayout.setHorizontalGroup(
            pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nmrklr)
                            .addComponent(txt_tglklr)
                            .addComponent(txt_ttlklr)
                            .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                                .addComponent(txt_iduss, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                        .addComponent(btn_savee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel)))
                .addGap(18, 18, 18)
                .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(txt_cari))
                .addContainerGap())
            .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dtlbrgklrLayout.setVerticalGroup(
            pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nmrklr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dtlbrgklrLayout.createSequentialGroup()
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tglklr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_ttlklr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_iduss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(pn_dtlbrgklrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel)
                            .addComponent(btn_hapus)
                            .addComponent(btn_update)
                            .addComponent(btn_savee))
                        .addGap(0, 186, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dtlbrgklr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dtlbrgklr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int selectedRow = tb_brgklr.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Diperbarui");
            return;
        }

        String no_klr = txt_nmrklr.getText();
        String tgl_klr = txt_tglklr.getText();
        String ttl_klr = txt_ttlklr.getText();
        String id_uss = txt_iduss.getText();

        if (no_klr.isEmpty() || tgl_klr.isEmpty() || ttl_klr.isEmpty() || id_uss.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi", "VALIDASI", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "UPDATE tbl_barangkeluar SET no_keluar=?, tgl_keluar=?, total_keluar=?, id_pengguna=? WHERE no_keluar=?";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, no_klr);
            st.setString(2, tgl_klr);
            st.setString(3, ttl_klr);
            st.setString(4, id_uss);
            st.setString(5, no_klr);

            int rowUpdate = st.executeUpdate();
            if (rowUpdate > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
                resetForm();
                getData();
            }

            st.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal melakukan pembaruan data: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format angka tidak valid: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
        }

        DefaultTableModel model = (DefaultTableModel) tb_brgklr.getModel();
        model.fireTableDataChanged();

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveeActionPerformed
        String no_klr = txt_nmrklr.getText();
        String tgl_klr = txt_tglklr.getText();
        String ttl_klr = txt_ttlklr.getText();
        String id_uss = txt_iduss.getText();

        if(no_klr.isEmpty()||tgl_klr.isEmpty() ||ttl_klr.isEmpty() ||id_uss.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO tbl_barangkeluar (no_keluar, tgl_keluar, total_keluar, id_pengguna) VALUES(?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, no_klr);
            st.setString(2, tgl_klr);
            st.setString(3, ttl_klr);
            st.setString(4, id_uss);

            int rowInserted = st.executeUpdate();
            if(rowInserted > 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");

                resetForm();
                getData();
            }

            st.close();
        } catch (Exception e) {
            Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_saveeActionPerformed

    private void txt_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cariMouseClicked
        txt_cari.setText("");
    }//GEN-LAST:event_txt_cariMouseClicked

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        DefaultTableModel model = (DefaultTableModel) tb_brgklr.getModel();
        model.setRowCount(0);

        String cari = txt_cari.getText();

        try{
            String sql = "Select * From tbl_barangkeluar WHERE no_keluar LIKE ?  OR tgl_keluar LIKE ? OR total_keluar LIKE ? OR id_pengguna LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1,"%" + cari + "%");
            st.setString(2,"%" + cari + "%");
            st.setString(3,"%" + cari + "%");
            st.setString(4,"%" + cari + "%");
            ResultSet rs = st.executeQuery();

            while(rs.next()){
                String no_klr = rs.getString("no_keluar");
                String tgl_klr = rs.getString("tgl_keluar");
                String ttl_klr = rs.getString("total_keluar");
                String id_uss = rs.getString("id_pengguna");

                Object[] rowData = {no_klr, tgl_klr, ttl_klr, id_uss};
                model.addRow(rowData);
            }

            rs.close();
            st.close();

        } catch (Exception e){
            Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tb_brgklr.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Dihapus");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapus Data Ini?", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if(confirm ==  JOptionPane.YES_OPTION){
            String no_klr = tb_brgklr.getValueAt(selectedRow, 0).toString();
            
            try {
                String sql = "DELETE FROM tbl_barangkeluar WHERE no_keluar=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, no_klr);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    resetForm();
                    getData();
                }
                
                st.close();
            } catch (Exception e) {
                Logger.getLogger(brngklr.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tb_brgklrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_brgklrMouseClicked
        // TODO add your handling code here:
        int selectedRow = tb_brgklr.getSelectedRow();
        if(selectedRow != -1){
            String no_keluar = tb_brgklr.getValueAt(selectedRow, 0).toString();
            String tgl = tb_brgklr.getValueAt(selectedRow, 1).toString();
            String total_klr = tb_brgklr.getValueAt(selectedRow, 2).toString();
            String iduser = tb_brgklr.getValueAt(selectedRow, 3).toString();
            
            

        
            txt_nmrklr.setText(no_keluar);
            txt_tglklr.setText(tgl);
            txt_ttlklr.setText(total_klr);
            txt_iduss.setText(iduser);
        }
    }//GEN-LAST:event_tb_brgklrMouseClicked

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        txt_nmrklr.setText("");
        txt_iduss.setText("");
        txt_ttlklr.setText("");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new listuser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_savee;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_dtlbrgklr;
    private javax.swing.JTable tb_brgklr;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_iduss;
    private javax.swing.JTextField txt_nmrklr;
    private javax.swing.JTextField txt_tglklr;
    private javax.swing.JTextField txt_ttlklr;
    // End of variables declaration//GEN-END:variables

    private void tanggal() {
        txt_tglklr.setEditable(false);
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        txt_tglklr.setText(tanggal);
    }
}
