/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author abdan
 */
import config.Koneksi;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import list.listbrg;
import list.listdistri;
import model.mod_transaksi;
public class pn_pesanbrg3 extends javax.swing.JPanel {

    
    

    private Connection conn;
    public pn_pesanbrg3() {
        initComponents();
        conn = Koneksi.getConnection();
        getData();
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tmbhpesan = new javax.swing.JPanel();
        txtnopesan = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        btnbatal1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtiddis = new javax.swing.JTextField();
        txtnamadis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtkdbrg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnamabrg = new javax.swing.JTextField();
        txthrg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjmlh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnupd = new javax.swing.JButton();
        txtsub = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dataPesan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpesan = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        tmbhpesan.setBackground(new java.awt.Color(255, 255, 255));
        tmbhpesan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        txtnopesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnopesanActionPerformed(evt);
            }
        });

        txttgl.setEnabled(false);

        btnbatal1.setText("Batal");
        btnbatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatal1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("No. Pemesanan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID Distributor");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nama Distributor");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Kode Barang");

        txtkdbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdbrgActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nama Barang");

        txthrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthrgActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Harga");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Jumlah");

        txtjmlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlhActionPerformed(evt);
            }
        });
        txtjmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjmlhKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TAMBAH PEMESANAN");

        btnupd.setText("Update");
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });

        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });
        txtsub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsubKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Sub Total");

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jButton1.setText("--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tmbhpesanLayout = new javax.swing.GroupLayout(tmbhpesan);
        tmbhpesan.setLayout(tmbhpesanLayout);
        tmbhpesanLayout.setHorizontalGroup(
            tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmbhpesanLayout.createSequentialGroup()
                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tmbhpesanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnopesan)
                            .addGroup(tmbhpesanLayout.createSequentialGroup()
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtkdbrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txtiddis, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))
                            .addComponent(txtnamabrg)
                            .addComponent(txtsub))
                        .addGap(66, 66, 66)
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(tmbhpesanLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txthrg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(tmbhpesanLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtnamadis, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtjmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tmbhpesanLayout.createSequentialGroup()
                                .addComponent(btnbatal1)
                                .addGap(18, 18, 18)
                                .addComponent(btntambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnupd))))
                    .addGroup(tmbhpesanLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        tmbhpesanLayout.setVerticalGroup(
            tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmbhpesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tmbhpesanLayout.createSequentialGroup()
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tmbhpesanLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel9))
                            .addGroup(tmbhpesanLayout.createSequentialGroup()
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtnamadis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txthrg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtjmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tmbhpesanLayout.createSequentialGroup()
                        .addComponent(txtnopesan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtiddis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(tmbhpesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(txtnamabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambah Pemesanan", tmbhpesan);

        dataPesan.setBackground(new java.awt.Color(255, 255, 255));
        dataPesan.setBorder(new javax.swing.border.MatteBorder(null));

        tblpesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Pesan", "Tanggal", "ID Distributor", "Nama Distributor", "Kode Barang", "Nama Barang", "Harga", "Jumlah", "Sub Total"
            }
        ));
        tblpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpesanMouseClicked(evt);
            }
        });
        tblpesan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblpesanKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblpesan);

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPesanLayout = new javax.swing.GroupLayout(dataPesan);
        dataPesan.setLayout(dataPesanLayout);
        dataPesanLayout.setHorizontalGroup(
            dataPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhapus)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        dataPesanLayout.setVerticalGroup(
            dataPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Data Pemesanan", dataPesan);

        jPanel1.add(jTabbedPane1, "card3");

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int selectedRow = tblpesan.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Dihapus");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapus Data Ini?", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if(confirm ==  JOptionPane.YES_OPTION){
            String no_pesan = tblpesan.getValueAt(selectedRow, 0).toString();
            
            try {
                String sql = "DELETE FROM transaksi WHERE no_pesan=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, no_pesan);
                
                int rowDelete = st.executeUpdate();
                if(rowDelete > 0){
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    resetForm();
                    getData();
                }
                
                st.close();
            } catch (Exception e) {
                Logger.getLogger(pn_pesanbrg3.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblpesanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpesanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpesanKeyTyped

    private void tblpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpesanMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblpesan.getSelectedRow();
        if(selectedRow != -1){
            String no_pesan = tblpesan.getValueAt(selectedRow, 0).toString();
            String tgl = tblpesan.getValueAt(selectedRow, 1).toString();
            String iddis = tblpesan.getValueAt(selectedRow, 2).toString();
            String namadis = tblpesan.getValueAt(selectedRow, 3).toString();
            String kd_brg = tblpesan.getValueAt(selectedRow, 4).toString();
            String nama_brg =tblpesan.getValueAt(selectedRow, 5).toString();
            String harga =tblpesan.getValueAt(selectedRow, 6).toString();
            String jumlah =tblpesan.getValueAt(selectedRow, 7).toString();
            String sub =tblpesan.getValueAt(selectedRow, 8).toString();
            

        
            txtnopesan.setText(no_pesan);
            txttgl.setText(tgl);
            txtiddis.setText(iddis);
            txtnamadis.setText(namadis);
            txtkdbrg.setText(kd_brg);
            txtnamabrg.setText(nama_brg);
            txthrg.setText(harga);
            txtjmlh.setText(jumlah);
            txtsub.setText(sub);
        }
    }//GEN-LAST:event_tblpesanMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String no_pesan = txtnopesan.getText();
        String tgl = txttgl.getText();
        String id_dis = txtiddis.getText();
        String nama_dis = txtnamabrg.getText();
        String kd_brg = txtkdbrg.getText();
        String nama_brg = txtnamabrg.getText();

        String hrg_brg = txthrg.getText();
        String jumlah = txtjmlh.getText();
        String sub = txtsub.getText();

        if(no_pesan.isEmpty() || tgl.isEmpty()||id_dis.isEmpty() || nama_dis.isEmpty() ||  kd_brg.isEmpty() || nama_brg.isEmpty() || hrg_brg.isEmpty()||jumlah.isEmpty()||sub.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String sql = "INSERT INTO transaksi (no_pesan, tanggal, id_distributor, nama_distributor, kode_barang, nama_barang, harga, jumlah, sub_total) VALUES(?,?,?,?,?,?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, no_pesan);
            st.setString(2, tgl);
            st.setString(3, id_dis);
            st.setString(4, nama_dis);
            st.setString(5, kd_brg);
            st.setString(6, nama_brg);
            st.setString(7, hrg_brg);
            st.setString(8, jumlah);
            st.setString(9, sub);

            int rowInserted = st.executeUpdate();
            if(rowInserted > 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                resetForm();
                getData();
            }

            st.close();
        } catch (Exception e) {
            Logger.getLogger(pn_brgtest.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtsubKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsubKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubKeyReleased

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblpesan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Baris Yang Akan Diperbarui");
            return;
        }
        String no_pesan = txtnopesan.getText();
        String tgl = txttgl.getText();
        String id_dis = txtiddis.getText();
        String nama_dis = txtnamadis.getText();
        String kd_brg = txtkdbrg.getText();
        String nama_brg = txtnamabrg.getText();
        String harga = txthrg.getText();
        String jumlah = txtjmlh.getText();
        String sub = txtsub.getText();

        if (no_pesan.isEmpty() || tgl.isEmpty() || id_dis.isEmpty() || nama_dis.isEmpty() || kd_brg.isEmpty() || nama_brg.isEmpty() || harga.isEmpty() || jumlah.isEmpty() || sub.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi", "VALIDASI", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "UPDATE transaksi SET no_pesan=?, tanggal=?, id_distributor=?, nama_distributor=?, kode_barang=?, nama_barang=?, harga=?, jumlah=?, sub_total=? WHERE no_pesan=?";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, no_pesan);
            st.setString(2, tgl);
            st.setString(3, id_dis);
            st.setString(4, nama_dis);
            st.setString(5, kd_brg);
            st.setString(6, nama_brg);
            st.setString(7, harga);
            st.setString(8, jumlah);
            st.setString(9, sub);
            st.setString(10, no_pesan);

            int rowUpdate = st.executeUpdate();
            if (rowUpdate > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
                resetForm();
                getData();
            }

            st.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal melakukan pembaruan data: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(pn_brgtest.class.getName()).log(Level.SEVERE, null, e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format angka tidak valid: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(pn_brgtest.class.getName()).log(Level.SEVERE, null, e);
        }

        DefaultTableModel model = (DefaultTableModel) tblpesan.getModel();
        model.fireTableDataChanged();

    }//GEN-LAST:event_btnupdActionPerformed

    private void txtjmlhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlhKeyReleased
        int a, b, c;
        a=Integer.valueOf(txthrg.getText());
        b=Integer.valueOf(txtjmlh.getText());
        c=a*b;
        txtsub.setText(""+c);
    }//GEN-LAST:event_txtjmlhKeyReleased

    private void txtjmlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtjmlhActionPerformed

    private void txthrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthrgActionPerformed

    private void txtkdbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdbrgActionPerformed

    private void btnbatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatal1ActionPerformed
        // TODO add your handling code here:
        txtnopesan.setText("");
        txttgl.setText("");
        txtiddis.setText("");
        txtnamadis.setText("");
        txtkdbrg.setText("");
        txtnamabrg.setText("");
        txthrg.setText("");
        txtjmlh.setText("");
        txtsub.setText("");
        txtnopesan.requestFocus();
    }//GEN-LAST:event_btnbatal1ActionPerformed

    private void txtnopesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnopesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopesanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new listdistri().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new listbrg().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal1;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupd;
    private javax.swing.JPanel dataPesan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblpesan;
    private javax.swing.JPanel tmbhpesan;
    private javax.swing.JTextField txthrg;
    private javax.swing.JTextField txtiddis;
    private javax.swing.JTextField txtjmlh;
    private javax.swing.JTextField txtkdbrg;
    private javax.swing.JTextField txtnamabrg;
    private javax.swing.JTextField txtnamadis;
    private javax.swing.JTextField txtnopesan;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tblpesan.getModel();
        model.setRowCount(0);
        
        try{
            String sql = "Select * From transaksi";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()){
                String pesan = rs.getString("no_pesan");
                String tgl = rs.getString("tanggal");
                String id_dis = rs.getString("id_distributor");
                String nama_dis = rs.getString("nama_distributor");
                String kd_brg = rs.getString("kode_barang");
                String nama_brg = rs.getString("nama_barang");
                String hrg = rs.getString("harga");
                String jumlah = rs.getString("jumlah");
                String sub = rs.getString("sub_total");
                
                
                
                Object[] rowData = {pesan, tgl, id_dis, nama_dis, kd_brg, nama_brg, hrg, jumlah, sub};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
            
        } catch (Exception e){
            Logger.getLogger(pn_pesanbrg3.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void total(){
        int numofrow = tblpesan.getRowCount();
 
    double total = 0;
    
     for (int i = 0; i < numofrow; i++) {
         
         double value = Double.valueOf(tblpesan.getValueAt(i, 8).toString());
         total += value ;
     }
    
    }

    private void resetForm() {
        txtnopesan.setText("");
        txttgl.setText("");
        txtiddis.setText("");
        txtnamadis.setText("");
        txtkdbrg.setText("");
        txtnamabrg.setText("");
        txthrg.setText("");
        txtjmlh.setText("");
        txtsub.setText("");
    }

    private void tanggal() {
        txttgl.setEditable(false);
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        txttgl.setText(tanggal);
    }

}
